<project name="kotlin-parser" default="compile">
    <target name="init">
        <uptodate property="parser.uptodate"
            targetfile="build/generated-java/org/parsers/kotlin/KotlinParser.java">
            <srcfiles dir="src/ccc" includes="*.ccc" />
        </uptodate>
    </target>

    <target name="clean">
        <delete dir="build" />
    </target>

    <target name="build-parser" depends="init" unless="parser.uptodate">
        <java fork="true" jar="bin/congocc.jar" failonerror="true">
            <assertions>
                <enable />
            </assertions>
            <arg line="-n -q -d ${basedir}/build/generated-java src/ccc/Kotlin.ccc" />
        </java>
    </target>

    <target name="compile" depends="build-parser">
        <javac destdir="build"
            deprecation="off"
            debug="on"
            optimize="off"
            failonerror="true"
            includeantruntime="false"
            release="17">
            <!--src path="src/java" /-->
            <src path="build/generated-java" />
        </javac>
    </target>
</project>
